### ISSUE TITLE
Fox injured not captured by mob canon

### ISSUE THREAD

**Issue by sarcasmaticly** [Slimefun-Addon-Community/MobCapturer#11]
Building a zoo on a survival world and fox are injured by the capture eggs, not captured. Holds true for all fox (red and snowy). 

We can capture Panda and polar bears, so it's not just the age of the mob in the game.

**Comment by J3fftw1** [comment]
this has been added in #8 only needs a merge

**Comment by sarcasmaticly** [comment]
I have passed this information along. Thank you!

**Comment by TheBusyBiscuit** [comment]
1. You did not follow the template.
2. Many mobs are not supported by this plugin, you can find a list of supported mobs in your Slimefun Guide. This isn't a bug.
