### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to MobCapturer

### ISSUE THREAD

**Issue by mav2020** [Slimefun-Addon-Community/MobCapturer#12]
## Description (Required)

When using the mob cannon, you cannot capture a mob. You get an error in console (see below) when you hit one with the pellet. There is no error for just using the cannon without hitting a mob. I am trying to find out from which update this started (Paper/Slimefun/MobCapturer), but figured I would put this in here while I look for more info to help you out.

## Steps to reproduce the Issue (Required)

Get a mob cannon and empty pellet.
Shoot a mob that can be captured.

## Expected behavior (Required)

Expected to capture a mob when shooting the pellet at the mob from the cannon.

## Server Log / Error Report

https://pastebin.com/eAQEnT6Q

## Environment (Required)

> sf versions
[13:49:57 INFO]: This Server uses the following setup of Slimefun:
[13:49:57 INFO]: Paper git-Paper-406 (MC: 1.16.4)
[13:49:57 INFO]: CS-CoreLib vDEV - 92 (git e9150d72)
[13:49:57 INFO]: Slimefun vDEV - 780 (git bc8d72b9)
[13:49:57 INFO]: Metrics build: #6
[13:49:57 INFO]:
[13:49:57 INFO]: Installed Addons: (1)
[13:49:57 INFO]:  MobCapturer vDEV - 12 (git 4f65d334)

**Comment by TheBusyBiscuit** [comment]
Please fill in the template.
Especially the steps to reproduce the issue and the expected behaviour are important!

**Comment by mav2020** [comment]
Noticed I missed that as soon as I submitted. I corrected it.

**Comment by GallowsDove** [comment]
Reproduceable on latest version of paper, should be fixed with #8
