### ISSUE TITLE
Mob capture works on protected areas

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/MobCapturer#15]
## Description (Required)

Mob capture works on protected areas if I don't have permission to area.
I tested with WorlGuard but maybe mob capture works on protected PlotSquared plot, protected Griefprevention claim, and protected Bentobox island.

## Steps to reproduce the Issue (Required)

1. Use Mob capturing cannon to steal mobs from protected areas.

https://www.youtube.com/watch?v=zwYwumaqaj4

## Expected behavior (Required)

Mob capture not work on protected areas if I don't have permission to area.

## Environment (Required)

Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
Slimefun DEV - 816 (git d3f4ca47)
Metrics-Module #21
Java 11

Installed Addons: (2)
  RestrictedCreative v2.4.6
  MobCapturer vDEV - 15 (git a42c9e0c)

**Comment by brasilcraft54** [comment]
![2021-08-26_19 29 36](https://user-images.githubusercontent.com/67756407/131046016-eff970e5-a8cc-42b0-ba0f-bb7d37fd0b2b.png)

I'm on paper 1.17.1 and I have the same problem with griefprevention

**Comment by brasilcraft54** [comment]
please fix this I would very much like to be able to use it on my server this plugin is amazing but buggy.
@TheBusyBiscuit
