### ISSUE TITLE
Bloodmoon Advanced and MobCapturer Bug Glitch

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun-Addon-Community/MobCapturer#26]
well I found a bug in the Bloodmoon Advanced and MobCapturer plugins

server and addons slimefun: https://prnt.sc/jmkljEFnfNgj
plugin Bloodmoon Advanced version: 4.5.3

video: https://www.youtube.com/watch?v=MQNuvas72q8

in Bloodmoon the monsters don't let the armor drop, but if I capture them, and release and kill the armor drop, making me get many armors and tools from the monsters
is there a way for mobcapture not to capture these blood moon monsters, or at least detect that it is a blood moon monster when released and be deleted?
People are abusing this and taking lots of armor.

**Comment by ybw0014** [comment]
@mrgeneralq Have a time to look at this again? Is there a publicly available API like [this](https://github.com/LoneDev6/API-ItemsAdder) so that I can add integration in?
