### ISSUE TITLE
Captured Zombie Villagers do not retain trades

### ISSUE THREAD

**Issue by EliteMasterEric** [Slimefun-Addon-Community/MobCapturer#32]
When capturing a Zombie Villager, the villager is reset to Novice and loses any trades it previously had.

**Comment by gphg** [comment]
Sounds like a feature for me. A cheaper way to reset the villager's job than one from Slimefun Core.

This is no different than just kill and repopulate. Very vanilla, required time and food.

**Comment by ybw0014** [comment]
The current API does not provide a way to retrieve the trades.
