### ISSUE TITLE
The category items for "tools" and "mob capturer" do not use their model numbers.

### ISSUE THREAD

**Issue by J1coding** [Slimefun-Addon-Community/MobCapturer#41]
### Checklist

- [X] You are using official version downloaded from Builds (https://thebusybiscuit.github.io/builds/)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

As discussed on Discord, when applying a custom texture pack with item-models.yml, the category items for both mobcapturer and tools do not display their designated textures and instead display the default textures.

### Reproduction Steps

1. Change the item-model.yml and use any custom resource pack that has textures for all the items
2. restart the server
3. Textures don't apply.

### Expected Behavior

The custom textures apply to both the mob capturer and items category items

### Server Software

Purpur

### Minecraft Version

1.20.x

### Slimefun version

![image](https://github.com/Slimefun-Addon-Community/MobCapturer/assets/113301471/c47a1798-d705-454d-a3e4-063c87e36c7f)

### Plugin version

vDEV - 91 (git 085b1a87)

**Comment by ybw0014** [comment]
[6fc26c3](https://github.com/Slimefun-Addon-Community/MobCapturer/commit/6fc26c35e9bd6a66303ec251acf6cea54c016a53)
main category: `MOB_CAPTURER`
tools category use same item of Mob Capturing Cannon
